disabled_rules:
  - trailing_whitespace
  - todo
  - class_delegate_protocol
opt_in_rules:
  - empty_count
  - force_unwrapping

analyzer_rules: # rules run by `swiftlint analyze`
  - explicit_self

included: # case-sensitive paths to include during linting. `--path` is ignored if present
excluded: # case-sensitive paths to ignore during linting. Takes precedence over `included`

# If true, SwiftLint will not fail if no lintable files are found.
allow_zero_lintable_files: false

# If true, SwiftLint will treat all warnings as errors.
strict: false

force_cast: warning
force_try:
  severity: warning

# 줄 길이 150으로 제한
line_length: 150

# 타입 네스팅 3 level에 경고 띄우기. (2 level 까지만 권장)
nesting:
  type_level:
    warning: 3
    error: 4

type_body_length:
  - 300 # warning
  - 400 # error

file_length:
  warning: 500
  error: 1200

type_name:
  min_length: 4
  max_length:
    warning: 40
    error: 50

reporter: "xcode"
