# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'FlipMate' do
  use_frameworks!
  inhibit_all_warnings!

  pod 'SwiftLint'
  pod 'GoogleSignIn'
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
      end
    end
  end

  target 'FlipMateTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FlipMateUITests' do
    # Pods for testing
  end

end
