# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FlipMate' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'SwiftLint'

  # Pods for FlipMate

  target 'FlipMateTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FlipMateUITests' do
    # Pods for testing
  end

end
